apiVersion: apps/v1
kind: Deployment
metadata:
  name: forward-proxy
spec:
  selector:
    matchLabels:
      app: forward-proxy
  template:
    metadata:
      labels:
        app: forward-proxy
    spec:
      containers:
      - name: forward-proxy
        image: ${NAMESPACE}/${IMAGE_NAME}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: forward-proxy-svc
spec:
  selector:
    app: forward-proxy
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

  